### ISSUE TITLE
Contributing the CLI tool back to CppSharp

### ISSUE THREAD

**Issue by tritao** [zillemarco/CSharpGenerator#1]
Hey, just came across this repo and noticed you're building a CLI tool to facilitate the generation of bindings using CppSharp.

Me and @ddobrev have been talking about adding such a tool to the main repository but haven't had the opportunity to do so yet due to other features.

I think such a tool would provide a much easier way to for people to play with generation of bindings.

Would you be interested in contributing this back to the main repo?

**Comment by zillemarco** [comment]
Well yes, I'll gladly help you if you think this could this be useful.
However one thing I noticed once I built this tool is that this will give very basic functionalities since the user won't be able to add custom passes and such. If you think this is acceptable I have nothing against adding this to CppSharp, just tell me how you would go on and do it.

**Comment by zillemarco** [comment]
Actually, after I answered you I thought about the problem of adding custom passes and such and maybe I've come up with a solution (loading a library like a plugin where the user adds his own things), so hopefully there won't be any limitations.

**Comment by tritao** [comment]
I like that idea, that would allow a lot of flexibility.

Another thing I had in mind is that we should provide CLI options that are compatible with GCC flags, so allow `-I` for include directories, and `-L` for library directories.

Feel free to open a PR against the main repo and we'll get it merged as-is and then can improve it with further patches.

**Comment by zillemarco** [comment]
Yeah, the CLI options I used are the first that came to my mind while coding this so aren't very standard.
About the pull request, do I need to fork CppSharp repo and add my code into it and then create the pull request? Sorry but I've never done this adding a whole repository before.

**Comment by ddobrev** [comment]
@zillemarco yes, this is how one works with pull requests.
About the plug-in, it sounds good to me too. However, since it would take time to complete it, I suggest merging your code to our repository first and then continuing your work.

**Comment by zillemarco** [comment]
All right, I'll clean the code a little bit since I've dirtied it with code for another project of mine and then I'll create the pull request.
Don't know if I'll be able to do that today though. Maybe later this night.

**Comment by tritao** [comment]
No rush, thanks for taking the time.

**Comment by zillemarco** [comment]
No problem at all, glad to be able to help!

**Comment by ddobrev** [comment]
@zillemarco let me add my own gratitude too. Also, we would like to rename your tool so that it starts with CppSharp. CppSharp.CLI is one option, where CLI means "command line interface". Would you have a suggestion of your own?

**Comment by zillemarco** [comment]
No problems about changing the name but I don't have any other suggestions since CppSharp.CLI seems the best to me too (that's what it is in the end).

**Comment by ddobrev** [comment]
Excellent. In such a case I think it would be easier to you to rename it (along with any relevant folders and other files, of course) before submitting your pull, not after.

**Comment by zillemarco** [comment]
Just finished doing it and pushed the commit to my (this) repo.
I'm not adding my whole repo since I have CppSharp as submodule so inside the CppSharp fork I'll create a folder named "CLI" inside the "src" folder and I'll put there my code, then later I'll finish the premake and I'll start working on the code as soon as I have a bit of time.

**Comment by ddobrev** [comment]
Sounds great, thank you. :)

**Comment by zillemarco** [comment]
Done, I've made the pull request. After you approve it and as soon as I have some time I'll continue with the work :)

**Comment by tritao** [comment]
I merged it, I will integrate it in the build system next.

**Comment by zillemarco** [comment]
All right. One last thing, do you prefer me to work on my fork or directly on a new or existing branch of CppSharp?

**Comment by tritao** [comment]
There are no advantages to working in a branch in the CppSharp repository directly. Working on your own fork is usually better and what me and @ddobrev usually do. It will also give you some better peace of mind when force pushing in case of a mistake.

The only exception is  when we want to save some in-progress code long-term in which case we push to a branch inside CppSharp.

By the way, in your pull request, there was a merge commit besides the one adding the new code. Those merge commits are not very desirable since they can screw up with the Git history making it non-linear. You should learn about Git rebase and force-push if you're not familiar with them to help fix those issues. 

If you need some help feel free to contact us or open issues.

**Comment by zillemarco** [comment]
I apologize for the merge commit inside my pull request, I think it happened because I had already made a fork of CppSharp and I wanted to align it with the mono/CppSharp master. I used GitHub desktop to this and it created the merge. I took a look at Git rebase, can I use this tool to align my fork with the original CppSharp?

**Comment by zillemarco** [comment]
@tritao no problem, after some googling I found out how to use rebase to update my fork so hopefully I won't cause more problems with the repository's history.
By the way, I'm not able to compile CppSharp with the debug configuration since the CppParser project can't find LLVM header files. This is due to the project looking for the files under LLVM's Debug installation folder, but the DownloadDependencies.bat I run downloaded the RelWithDebInfo folder. Is this a known behaviour and I need to do something else to be able to compile with the debug configuration or should I open an issue on the main repository?

**Comment by ddobrev** [comment]
@zillemarco the LLVM binaries we use are compiled RelWithDebInfo and you cannot use them in a debug build. What you can do is set our C++ projects (such as the parser) to RelWithDebInfo and everything else to Debug. However, this is not really necessary since managed code can be reliably debugged in release too. All you need to to in order to step into native code is tick "Enable native code debugging" in the Debug tab of the properties of whichever start-up project you choose.

**Comment by zillemarco** [comment]
Oh ok. No problems then, I'll do like that. Thanks!
